export const SEARCH_MOVIE_URL = "https://api.themoviedb.org/3/search/movie";
export const API_AUTH_KEY = process.env.NEXT_PUBLIC_API_AUTH_KEY;

export const UPCOMING_LIST =
  "https://api.themoviedb.org/3/movie/upcoming?language=en-US&page=1";

export const IMAGE_CONFIG = {
  base_url: "https://image.tmdb.org/t/p/",
  backdrop_sizes: {
    w300: "w300",
    w780: "w780",
    w1280: "w1280",
    original: "original",
  },
  logo_sizes: {
    w45: "w45",
    w92: "w92",
    w154: "w154",
    w185: "w185",
    w300: "w300",
    w500: "w500",
    original: "original",
  },
  poster_sizes: {
    w92: "w92",
    w154: "w154",
    w185: "w185",
    w342: "w342",
    w500: "w500",
    w780: "w780",
    original: "original",
  },
  profile_sizes: {
    w45: "w45",
    w185: "w185",
    h632: "h632",
    original: "original",
  },
  still_sizes: {
    w92: "w92",
    w185: "w185",
    w300: "w300",
    original: "original",
  },
  change_keys: {
    adult: "adult",
    air_date: "air_date",
    also_known_as: "also_known_as",
    alternative_titles: "alternative_titles",
    biography: "biography",
    birthday: "birthday",
    budget: "budget",
    cast: "cast",
    certifications: "certifications",
    character_names: "character_names",
    created_by: "created_by",
    crew: "crew",
    deathday: "deathday",
    episode: "episode",
    episode_number: "episode_number",
    episode_run_time: "episode_run_time",
    freebase_id: "freebase_id",
    freebase_mid: "freebase_mid",
    general: "general",
    genres: "genres",
    guest_stars: "guest_stars",
    homepage: "homepage",
    images: "images",
    imdb_id: "imdb_id",
    languages: "languages",
    name: "name",
    network: "network",
    origin_country: "origin_country",
    original_name: "original_name",
    original_title: "original_title",
    overview: "overview",
    parts: "parts",
    place_of_birth: "place_of_birth",
    plot_keywords: "plot_keywords",
    production_code: "production_code",
    production_companies: "production_companies",
    production_countries: "production_countries",
    releases: "releases",
    revenue: "revenue",
    runtime: "runtime",
    season: "season",
    season_number: "season_number",
    season_regular: "season_regular",
    spoken_languages: "spoken_languages",
    status: "status",
    tagline: "tagline",
    title: "title",
    translations: "translations",
    tvdb_id: "tvdb_id",
    tvrage_id: "tvrage_id",
    type: "type",
    video: "video",
    videos: "videos",
  },
};
